name: update snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: anshulyadavv
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Update snake'
